#!/bin/bash

# killer is xkill reverse engineered made in order to fix a problem noticed in the xkill command 
# the bug was that when xkill was used to kill a process, you could also kill the desktop 
# and the only way to fix it was to restart the computer

window_id=$(xdotool selectwindow)

if [ -n "$window_id" ]; then

    window_name=$(xprop -id $window_id _NET_WM_NAME | awk -F '"' '{print $2}')

    if [[ "$window_name" == *"Desktop"* ]]; then
	    echo "No application window to close or background selected." 
    fi
    
    pid=$(xprop _NET_WM_PID -id $window_id | awk '/_NET_WM_PID\(CARDINAL\)/{print $3}')
    
    if [ -n "$pid" ]; then
        echo "Killing process with PID: $pid"
        kill $pid
    else
        echo "Failed to retrieve PID for window."
    fi
else
    echo "No window selected."
fi
