#!/usr/bin/env bash

#execute to shutdown 
#-s for sleep 
#-l for logout 

case "$1" in
  -h | --help)
    echo "Usage: $0 [-s | -l | -h]"
    echo "  -s: Sleep the system"
    echo "  -l: Log out of the current session"
    echo "  -h: Display this help message"
    exit 0
    ;; 
  -s)
    echo "Going to sleep..."
    systemctl suspend
    ;;
  -l)
    echo "Logging out..."
    gnome-session-quit --logout --no-prompt
    ;;
  *)
    echo "Shutting down..."
    echo "Press ^C to cancel" 
    sleep  5
    systemctl poweroff
    ;;
esac