#!/usr/bin/env bash

#execute to shutdown 
#-s for sleep 
#-l for logout 
#-t for timer [seconds]

case "$1" in
  -s)
    echo "Going to sleep..."
    systemctl suspend
    ;;
  -l)
    echo "Logging out..."
    gnome-session-quit --logout --no-prompt
    ;;
  -t) 
   if [ -z "$2" ]; then
      timer=15
    else
      timer="$2"
    fi
    echo "Dying... in $timer seconds"
    sleep "$timer"
    systemctl poweroff
    ;;
  *)
    echo "Shutting down..."
    echo "Press ^C to cancel" 
    sleep  5
    systemctl poweroff
    ;;
esac